Total Instances: 81

Total Correct: 71
Total Runtime Failed: 4
Total Compilation Failed: 2
Total Test Failed: 3
Total Infinite Loop: 1

Accuracy: 87.65432098765432
Runtime Rate: 4.938271604938271
Compilation Rate: 2.4691358024691357
Test Failed Rate: 3.7037037037037033
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['codeforces_147_A.py', 'atcoder_ARC062_B.py', 'codeforces_58_B.py'] 
Failed Test Details: ['Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035\n244345\n146607\n48869\n15\n5\n3\n1\n', 'Filename: codeforces_147_A.py Actual: a! n, to\n Generated: a ! n  ,  to\n', 'Filename: atcoder_ARC062_B.py Actual: 0\n Generated: -1\n'] 
=================================================================================================
Runtime Error Files: ['atcoder_ABC051_A.py', 'atcoder_ABC125_A.py', 'codeforces_306_A.py', 'codeforces_96_B.py'] 
Runtime Error Details: ['Filename: atcoder_ABC125_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/atcoder_ABC125_A.py", line 8, in <module>\n    result = atcoder_ABC125_A()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/atcoder_ABC125_A.py", line 2, in atcoder_ABC125_A\n    n, k, m, l, a, b, c = map(int, input().split())\nValueError: not enough values to unpack (expected 7, got 3)\n', 'Filename: codeforces_96_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/codeforces_96_B.py", line 22, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/codeforces_96_B.py", line 17, in main\n    value = int(s, 2)\nValueError: invalid literal for int() with base 2: \'74\'\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 4, in <module>\n    a, b, c = re.split(\',\', input_str)\nValueError: too many values to unpack (expected 3)\n', 'Filename: codeforces_306_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/codeforces_306_A.py", line 18, in <module>\n    n = fr.next_double()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/gpt-3.5/avatar/java/python-sanitized/codeforces_306_A.py", line 14, in next_double\n    return float(self.lines[self.pointer - 1])\nValueError: could not convert string to float: \'87 34\\n\'\n'] 
=================================================================================================
Compilation Error Files: ['atcoder_AGC007_C.py', 'atcoder_ABC178_B.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
