Total Instances: 81

Total Correct: 38
Total Runtime Failed: 26
Total Compilation Failed: 8
Total Test Failed: 8
Total Infinite Loop: 1

Accuracy: 46.913580246913575
Runtime Rate: 32.098765432098766
Compilation Rate: 9.876543209876543
Test Failed Rate: 9.876543209876543
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['atcoder_ABC042_A.py', 'codeforces_58_B.py', 'atcoder_ABC151_A.py', 'atcoder_AGC046_B.py', 'codeforces_110_B.py', 'codeforces_96_B.py', 'atcoder_AGC046_A.py', 'atcoder_ABC132_F.py'] 
Failed Test Details: ['Filename: atcoder_AGC046_A.py Actual: 360\n Generated: Input must be a single integer.\n', 'Filename: atcoder_ABC132_F.py Actual: 147\n Generated: 1000\n', 'Filename: atcoder_ABC151_A.py Actual: d\n Generated: 100\n', 'Filename: codeforces_110_B.py Actual: abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd Generated: abcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\n', 'Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035\n244345\n48869\n1\n', 'Filename: atcoder_ABC042_A.py Actual: YES\n Generated: NO\n', 'Filename: atcoder_AGC046_B.py Actual: 65\n Generated: 17\n', 'Filename: codeforces_96_B.py Actual: 4444477777\n Generated: '] 
=================================================================================================
Runtime Error Files: ['codeforces_544_B.py', 'codeforces_189_A.py', 'codeforces_334_A.py', 'atcoder_ABC124_A.py', 'codeforces_171_A.py', 'codeforces_99_A.py', 'atcoder_ABC070_B.py', 'codeforces_8_B.py', 'codeforces_30_A.py', 'atcoder_ABC155_E.py', 'atcoder_ABC153_A.py', 'codeforces_147_A.py', 'atcoder_ABC139_B.py', 'codeforces_369_B.py', 'codeforces_569_A.py', 'atcoder_AGC006_B.py', 'atcoder_ABC122_D.py', 'atcoder_ABC169_C.py', 'atcoder_ABC051_A.py', 'codeforces_79_A.py', 'atcoder_ABC114_C.py', 'atcoder_ABC132_A.py', 'atcoder_ABC168_C.py', 'atcoder_ARC102_C.py', 'codeforces_678_A.py', 'atcoder_ABC170_A.py'] 
Runtime Error Details: ['Filename: atcoder_ABC139_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC139_B.py", line 1, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'8 8\'\n', 'Filename: atcoder_ABC168_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 9 49\'\n', 'Filename: codeforces_544_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_544_B.py", line 2, in <module>\n    printIsland(n, count)\nNameError: name \'printIsland\' is not defined\n', 'Filename: codeforces_171_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_171_A.py", line 8, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'35005211 521595368\'\n', 'Filename: atcoder_ABC132_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC132_A.py", line 59, in <module>\n    s = sc.next()\nAttributeError: \'dict\' object has no attribute \'next\'\n', 'Filename: codeforces_678_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_678_A.py", line 1, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'999999999 1\'\n', 'Filename: atcoder_ABC153_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC153_A.py", line 1, in <module>\n    monsterHP = int(input())\nValueError: invalid literal for int() with base 10: \'10000 1\'\n', 'Filename: atcoder_ABC170_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 14, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 4, in main\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 3 4 0\'\n', 'Filename: atcoder_AGC006_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 31, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 4, in main\n    for _ in range(int(input())):\nValueError: invalid literal for int() with base 10: \'2 1\'\n', 'Filename: atcoder_ABC124_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 11, in <module>\n    print(solve())\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 2, in solve\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'6 6\'\n', 'Filename: atcoder_ARC102_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ARC102_C.py", line 8, in <module>\n    nchoosek[i][j] = (nchoosek[i - 1][j] + nchoosek[i - 1][j - 1]) % mod\nIndexError: list index out of range\n', 'Filename: atcoder_ABC114_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC114_C.py", line 4, in <module>\n    S = input()\nEOFError: EOF when reading a line\n', 'Filename: codeforces_334_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_334_A.py", line 20, in <module>\n    print(odd.pop(0) + " " + even.pop(), end=" ")\nTypeError: unsupported operand type(s) for +: \'int\' and \'str\'\n', 'Filename: atcoder_ABC122_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 35, in <module>\n    ins = atcoder_ABC122_D()\nNameError: name \'atcoder_ABC122_D\' is not defined\n', 'Filename: codeforces_369_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_369_B.py", line 3, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'1 1 1 1 1 1\'\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 8, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 4, in main\n    a, b, c = sys.stdin.readline().strip().split()\nValueError: not enough values to unpack (expected 3, got 1)\n', 'Filename: codeforces_99_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_99_A.py", line 23, in <module>\n    tests = int(input())\nValueError: invalid literal for int() with base 10: \'8.3\'\n', 'Filename: codeforces_8_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_8_B.py", line 40, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_8_B.py", line 18, in main\n    co[0][k] = x\nIndexError: list assignment index out of range\n', 'Filename: atcoder_ABC070_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC070_B.py", line 13, in <module>\n    if array[i] == 2:\nNameError: name \'array\' is not defined\n', 'Filename: codeforces_30_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_30_A.py", line 3, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'7 896 7\'\n', 'Filename: atcoder_ABC169_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 11, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 4, in main\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'814793613347395 1.99\'\n', 'Filename: codeforces_569_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_569_A.py", line 18, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_569_A.py", line 11, in main\n    t = int(input())\nValueError: invalid literal for int() with base 10: \'100000 3125 2\'\n', 'Filename: codeforces_79_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_79_A.py", line 41, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_79_A.py", line 9, in main\n    with open(\'input.txt\', \'r\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'input.txt\'\n', 'Filename: codeforces_147_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_147_A.py", line 16, in <module>\n    sb = StringBuilder()\nNameError: name \'StringBuilder\' is not defined\n', 'Filename: atcoder_ABC155_E.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC155_E.py", line 36, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC155_E.py", line 31, in main\n    dp[i] = get_dp(c[i], i, 0)\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/atcoder_ABC155_E.py", line 19, in get_dp\n    dp[0][i] = min(dp[0][i], dp[i+1][j] + tmp + k)\nIndexError: list index out of range\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_189_A.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/misleading_test/mistral/avatar/java/python-sanitized/codeforces_189_A.py", line 4, in main\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\'\n'] 
=================================================================================================
Compilation Error Files: ['atcoder_AGC002_A.py', 'atcoder_AGC025_A.py', 'codeforces_306_A.py', 'codeforces_203_A.py', 'codeforces_55_A.py', 'atcoder_AGC007_C.py', 'codeforces_678_B.py', 'atcoder_ABC172_D.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
