Total Instances: 81

Total Correct: 60
Total Runtime Failed: 3
Total Compilation Failed: 9
Total Test Failed: 8
Total Infinite Loop: 1

Accuracy: 74.07407407407408
Runtime Rate: 3.7037037037037033
Compilation Rate: 11.11111111111111
Test Failed Rate: 9.876543209876543
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['codeforces_373_B.py', 'codeforces_58_B.py', 'atcoder_ABC155_E.py', 'atcoder_ABC051_A.py', 'codeforces_96_B.py', 'atcoder_ABC168_C.py', 'codeforces_203_A.py', 'atcoder_ABC114_C.py'] 
Failed Test Details: ['Filename: atcoder_ABC155_E.py Actual: 1\n Generated: 0\n', 'Filename: codeforces_203_A.py Actual: NO\n Generated: YES\n', 'Filename: atcoder_ABC051_A.py Actual: pnxnn asadasd asdasf\n\n Generated: pnxnn muduhzn aquud \n', 'Filename: codeforces_96_B.py Actual: 4444477777\n Generated: 7444447777\n', 'Filename: atcoder_ABC114_C.py Actual: 8335\n Generated: 8335.0\n', 'Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035\n244345\n48869\n1\n', 'Filename: codeforces_373_B.py Actual: 635520\n Generated: 635520.0\n', 'Filename: atcoder_ABC168_C.py Actual: 1.000076150972172\n Generated: 1.5567281636978751\n'] 
=================================================================================================
Runtime Error Files: ['codeforces_99_A.py', 'codeforces_514_A.py', 'atcoder_ABC132_F.py'] 
Runtime Error Details: ['Filename: codeforces_99_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/starcoder2/avatar/java/python-sanitized/codeforces_99_A.py", line 4, in <module>\n    if sys.argv[1] == \'local\':\nIndexError: list index out of range\n', 'Filename: codeforces_514_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/starcoder2/avatar/java/python-sanitized/codeforces_514_A.py", line 20, in <module>\n    newNumber = newNumber + list[i] * (10 ** pow)\nOverflowError: int too large to convert to float\n', 'Filename: atcoder_ABC132_F.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/starcoder2/avatar/java/python-sanitized/atcoder_ABC132_F.py", line 13, in <module>\n    q = len(len)\nTypeError: \'list\' object is not callable\n'] 
=================================================================================================
Compilation Error Files: ['atcoder_ARC062_B.py', 'codeforces_30_A.py', 'codeforces_32_B.py', 'atcoder_AGC007_C.py', 'atcoder_AGC046_A.py', 'codeforces_86_A.py', 'codeforces_79_A.py', 'codeforces_369_B.py', 'codeforces_651_A.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
