Total Instances: 81

Total Correct: 52
Total Runtime Failed: 10
Total Compilation Failed: 8
Total Test Failed: 9
Total Infinite Loop: 2

Accuracy: 64.19753086419753
Runtime Rate: 12.345679012345679
Compilation Rate: 9.876543209876543
Test Failed Rate: 11.11111111111111
Infinite Loop Rate: 2.4691358024691357

=================================================================================================
Failed Test Files: ['atcoder_ABC114_C.py', 'atcoder_ABC172_D.py', 'atcoder_ABC125_A.py', 'atcoder_ABC042_A.py', 'codeforces_514_A.py', 'codeforces_622_A.py', 'atcoder_ARC062_B.py', 'codeforces_110_B.py', 'atcoder_ABC136_B.py'] 
Failed Test Details: ['Filename: atcoder_ABC136_B.py Actual: 90909\n Generated: 90909.0\n', 'Filename: codeforces_514_A.py Actual: 4221\n Generated: 4221.0\n', 'Filename: codeforces_622_A.py Actual: 311 Generated: 311.0\n', 'Filename: atcoder_ABC125_A.py Actual: 0\n Generated: 20\n', 'Filename: atcoder_ABC042_A.py Actual: YES\n Generated: NO\n', 'Filename: codeforces_110_B.py Actual: abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd Generated: abcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\nabcd\n', 'Filename: atcoder_ABC114_C.py Actual: 8335\n Generated: 2539\n', 'Filename: atcoder_ARC062_B.py Actual: 0\n Generated: -1\n', 'Filename: atcoder_ABC172_D.py Actual: 837779626111757\n Generated: 60516669315452\n'] 
=================================================================================================
Runtime Error Files: ['codeforces_189_A.py', 'codeforces_306_A.py', 'atcoder_ABC051_A.py', 'codeforces_96_B.py', 'codeforces_99_A.py', 'codeforces_334_A.py', 'atcoder_ABC132_F.py', 'atcoder_ABC169_C.py', 'atcoder_ABC174_C.py', 'atcoder_ARC102_C.py'] 
Runtime Error Details: ['Filename: atcoder_ABC169_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ABC169_C.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'814793613347395 1.99\'\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 6, in <module>\n    a, b, c = input_str.split(",")\nValueError: too many values to unpack (expected 3)\n', 'Filename: codeforces_99_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_99_A.py", line 42, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_99_A.py", line 4, in main\n    if sys.getproperty("ONLINE_JUDGE") is None:\nAttributeError: module \'sys\' has no attribute \'getproperty\'\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_189_A.py", line 14, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_189_A.py", line 4, in main\n    n = int(sys.stdin.readline().strip())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\'\n', 'Filename: atcoder_ARC102_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ARC102_C.py", line 39, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ARC102_C.py", line 17, in main\n    k = int(input())\nValueError: invalid literal for int() with base 10: \'1 200000\'\n', 'Filename: codeforces_306_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_306_A.py", line 46, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_306_A.py", line 38, in main\n    n = fr.next_double()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_306_A.py", line 20, in next_double\n    return float(self.next())\nValueError: could not convert string to float: \'87 34\'\n', 'Filename: atcoder_ABC174_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ABC174_C.py", line 27, in <module>\n    print(solve(n))\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ABC174_C.py", line 11, in solve\n    set = set()\nUnboundLocalError: local variable \'set\' referenced before assignment\n', 'Filename: codeforces_96_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_96_B.py", line 28, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_96_B.py", line 23, in main\n    value = int(s, 2)\nValueError: invalid literal for int() with base 2: \'74\'\n', 'Filename: codeforces_334_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/codeforces_334_A.py", line 21, in <module>\n    print(even.pop(even.size() - 1), end=" ")\nAttributeError: \'list\' object has no attribute \'size\'\n', 'Filename: atcoder_ABC132_F.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ABC132_F.py", line 22, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/codellama/avatar/java/python-sanitized/atcoder_ABC132_F.py", line 12, in main\n    q = len.size()\nAttributeError: \'list\' object has no attribute \'size\'\n'] 
=================================================================================================
Compilation Error Files: ['codeforces_203_A.py', 'atcoder_ABC178_A.py', 'atcoder_AGC007_C.py', 'codeforces_58_B.py', 'atcoder_AGC025_A.py', 'atcoder_ABC151_A.py', 'codeforces_579_A.py', 'codeforces_678_A.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py', 'codeforces_340_A.py'] 
=================================================================================================
