Total Instances: 86

Total Correct: 16
Total Runtime Failed: 23
Total Compilation Failed: 30
Total Test Failed: 17
Total Infinite Loop: 0

Accuracy: 18.6046511627907
Runtime Rate: 26.744186046511626
Compilation Rate: 34.883720930232556
Test Failed Rate: 19.767441860465116
Infinite Loop Rate: 0.0

=================================================================================================
Failed Test Files: ['codeforces_672_A.py', 'codeforces_678_B.py', 'atcoder_ABC051_A.py', 'codeforces_96_B.py', 'atcoder_ABC124_C.py', 'codeforces_147_A.py', 'atcoder_ARC062_B.py', 'codeforces_55_A.py', 'codeforces_579_A.py', 'codeforces_669_A.py', 'codeforces_276_B.py', 'codeforces_459_A.py', 'atcoder_ABC149_B.py', 'codeforces_30_A.py', 'codeforces_32_B.py', 'atcoder_ABC136_B.py', 'codeforces_79_A.py'] 
Failed Test Details: ['Filename: atcoder_ABC051_A.py Actual: pnxnn asadasd asdasf\n\n Generated: pnxnn,muduhzn,aquud,\n  \n', 'Filename: codeforces_96_B.py Actual: 4444477777\n Generated: 74\n', 'Filename: codeforces_678_B.py Actual: 2108\n Generated: ', 'Filename: codeforces_672_A.py Actual: 3 Generated: 2\n', 'Filename: codeforces_30_A.py Actual: 2\n Generated: ', 'Filename: atcoder_ABC149_B.py Actual: 0 1000000000000 Generated: 1000000000000 1000000000000\n', 'Filename: codeforces_276_B.py Actual: Second\n Generated: ', 'Filename: codeforces_55_A.py Actual: YES\n Generated: ', 'Filename: codeforces_79_A.py Actual: Ciel\n Generated: ', 'Filename: codeforces_579_A.py Actual: 2\n Generated: ', 'Filename: codeforces_459_A.py Actual: 4 4 0 0 Generated: ', 'Filename: codeforces_32_B.py Actual: 00\n Generated: 002\n', 'Filename: atcoder_ABC136_B.py Actual: 90909\n Generated: -9090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090909090809091\n', 'Filename: atcoder_ABC124_C.py Actual: 0\n Generated: 1\n', 'Filename: codeforces_669_A.py Actual: 666666661\n Generated: ', 'Filename: codeforces_147_A.py Actual: a! n, to\n Generated: ', 'Filename: atcoder_ARC062_B.py Actual: 0\n Generated: -1\n'] 
=================================================================================================
Runtime Error Files: ['atcoder_ABC042_A.py', 'atcoder_ABC153_A.py', 'codeforces_379_A.py', 'atcoder_AGC002_A.py', 'codeforces_678_A.py', 'atcoder_ABC164_D.py', 'atcoder_ABC125_A.py', 'atcoder_ABC170_A.py', 'codeforces_58_B.py', 'codeforces_622_A.py', 'atcoder_ABC139_B.py', 'atcoder_AGC006_B.py', 'atcoder_ABC143_A.py', 'atcoder_ABC135_D.py', 'atcoder_ABC124_A.py', 'atcoder_ABC149_C.py', 'atcoder_ABC164_A.py', 'atcoder_ABC168_C.py', 'atcoder_ABC120_C.py', 'codeforces_171_A.py', 'codeforces_544_B.py', 'atcoder_ABC129_E.py', 'codeforces_334_A.py'] 
Runtime Error Details: ['Filename: atcoder_ABC139_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC139_B.py", line 3, in <module>\n    a = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'8 8\\n\'\n', 'Filename: atcoder_ABC129_E.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC129_E.py", line 3, in <module>\n    n = int(sys.stdin.readline())\nValueError: Exceeds the limit (4300) for integer string conversion: value has 99381 digits; use sys.set_int_max_str_digits() to increase the limit\n', 'Filename: atcoder_AGC006_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 32, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_AGC006_B.py", line 4, in main\n    n = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'2 1\\n\'\n', 'Filename: codeforces_678_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_678_A.py", line 1, in <module>\n    n = int(input())\nValueError: invalid literal for int() with base 10: \'999999999 1\'\n', 'Filename: atcoder_ABC124_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC124_A.py", line 1, in <module>\n    import java.util\nModuleNotFoundError: No module named \'java\'\n', 'Filename: atcoder_ABC164_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC164_D.py", line 3, in <module>\n    N = int(sys.stdin.readline())\nValueError: Exceeds the limit (4300) for integer string conversion: value has 200000 digits; use sys.set_int_max_str_digits() to increase the limit\n', 'Filename: atcoder_ABC149_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC149_C.py", line 22, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC149_C.py", line 10, in main\n    for i in range(2, mid + 1):\nTypeError: \'float\' object cannot be interpreted as an integer\n', 'Filename: atcoder_ABC143_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC143_A.py", line 3, in <module>\n    A = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'75 25\\n\'\n', 'Filename: codeforces_379_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_379_A.py", line 1, in <module>\n    import java.util\nModuleNotFoundError: No module named \'java\'\n', 'Filename: codeforces_544_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_544_B.py", line 3, in <module>\n    n = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'100 10000\\n\'\n', 'Filename: atcoder_ABC153_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC153_A.py", line 3, in <module>\n    monsterHP = int(sys.stdin.readline().strip())\nValueError: invalid literal for int() with base 10: \'10000 1\'\n', 'Filename: atcoder_ABC135_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC135_D.py", line 28, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC135_D.py", line 23, in main\n    dp[i][j] = dp[i - 1][map[l]]\nTypeError: \'type\' object is not subscriptable\n', 'Filename: atcoder_ABC168_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC168_C.py", line 3, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'1 2 9 49\'\n', 'Filename: codeforces_334_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_334_A.py", line 1, in <module>\n    import java.io\nModuleNotFoundError: No module named \'java\'\n', 'Filename: atcoder_ABC164_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC164_A.py", line 1, in <module>\n    import java.util\nModuleNotFoundError: No module named \'java\'\n', 'Filename: codeforces_171_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_171_A.py", line 3, in <module>\n    a = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'35005211 521595368\\n\'\n', 'Filename: atcoder_AGC002_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_AGC002_A.py", line 3, in <module>\n    a = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'-1000000000 -1\\n\'\n', 'Filename: atcoder_ABC125_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC125_A.py", line 3, in <module>\n    n, k, m, l, a, b, c = map(int, sys.stdin.readline().split())\nValueError: not enough values to unpack (expected 7, got 3)\n', 'Filename: atcoder_ABC042_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC042_A.py", line 25, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC042_A.py", line 4, in main\n    num_1 = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'5 5 7\\n\'\n', 'Filename: atcoder_ABC120_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC120_C.py", line 22, in <module>\n    print(ans * 2)\nNameError: name \'ans\' is not defined. Did you mean: \'abs\'?\n', 'Filename: codeforces_58_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_58_B.py", line 6, in <module>\n    if m % i == 0:\nZeroDivisionError: integer division or modulo by zero\n', 'Filename: codeforces_622_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/codeforces_622_A.py", line 4, in <module>\n    n = (int)((math.sqrt(1 + (8 * n1)) - 1) / 2)\nNameError: name \'math\' is not defined\n', 'Filename: atcoder_ABC170_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 14, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/llama2/avatar/java/python-sanitized/atcoder_ABC170_A.py", line 7, in main\n    x = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'1 2 3 4 0\\n\'\n'] 
=================================================================================================
Compilation Error Files: ['atcoder_ABC043_B.py', 'atcoder_ABC151_A.py', 'atcoder_ABC132_F.py', 'atcoder_AGC046_A.py', 'atcoder_AGC025_A.py', 'atcoder_ABC122_D.py', 'atcoder_ARC102_C.py', 'atcoder_AGC034_B.py', 'codeforces_86_A.py', 'codeforces_8_B.py', 'codeforces_92_A.py', 'codeforces_110_B.py', 'codeforces_369_B.py', 'codeforces_514_A.py', 'codeforces_340_A.py', 'atcoder_ABC169_D.py', 'atcoder_ABC114_C.py', 'codeforces_99_A.py', 'atcoder_ABC155_E.py', 'atcoder_AGC046_B.py', 'codeforces_569_A.py', 'atcoder_ABC132_A.py', 'atcoder_AGC007_C.py', 'atcoder_ABC169_C.py', 'codeforces_49_A.py', 'codeforces_203_A.py', 'codeforces_189_A.py', 'codeforces_190_A.py', 'codeforces_306_A.py', 'codeforces_373_B.py'] 
=================================================================================================
Infinite Loop Files: [] 
=================================================================================================
