Total Instances: 81

Total Correct: 70
Total Runtime Failed: 4
Total Compilation Failed: 3
Total Test Failed: 3
Total Infinite Loop: 1

Accuracy: 86.41975308641975
Runtime Rate: 4.938271604938271
Compilation Rate: 3.7037037037037033
Test Failed Rate: 3.7037037037037033
Infinite Loop Rate: 1.2345679012345678

=================================================================================================
Failed Test Files: ['atcoder_ARC062_B.py', 'codeforces_58_B.py', 'codeforces_678_A.py'] 
Failed Test Details: ['Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035\n244345\n48869\n1\n', 'Filename: atcoder_ARC062_B.py Actual: 0\n Generated: -1\n', 'Filename: codeforces_678_A.py Actual: 1000000000\n Generated: 999999999\n'] 
=================================================================================================
Runtime Error Files: ['atcoder_ABC122_D.py', 'atcoder_ABC051_A.py', 'codeforces_96_B.py', 'codeforces_189_A.py'] 
Runtime Error Details: ['Filename: atcoder_ABC122_D.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 27, in <module>\n    print(dfs(0, "TTT"))\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 22, in dfs\n    if is_ok(last3[1:] + c):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/atcoder_ABC122_D.py", line 11, in is_ok\n    vals[i], vals[i + 1] = vals[i + 1], vals[i]\nIndexError: list index out of range\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/codeforces_189_A.py", line 16, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/codeforces_189_A.py", line 4, in main\n    n = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\\n\'\n', 'Filename: atcoder_ABC051_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 8, in <module>\n    main()\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/atcoder_ABC051_A.py", line 4, in main\n    a, b, c = map(str, sys.stdin.readline().split(\',\'))\nValueError: too many values to unpack (expected 3)\n', 'Filename: codeforces_96_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/codeforces_96_B.py", line 18, in <module>\n    print(find_next_number(number))\n  File "/home/ali/Documents/CodeMind/translation_output/w_test/magicoder/avatar/java/python-sanitized/codeforces_96_B.py", line 12, in find_next_number\n    value = int(binary_str, 2)\nValueError: invalid literal for int() with base 2: \'74\'\n'] 
=================================================================================================
Compilation Error Files: ['codeforces_55_A.py', 'atcoder_AGC007_C.py', 'atcoder_ABC164_A.py'] 
=================================================================================================
Infinite Loop Files: ['codeforces_669_A.py'] 
=================================================================================================
