Total Instances: 86

Total Correct: 57
Total Runtime Failed: 10
Total Compilation Failed: 7
Total Test Failed: 10
Total Infinite Loop: 2

Accuracy: 66.27906976744185
Runtime Rate: 11.627906976744185
Compilation Rate: 8.13953488372093
Test Failed Rate: 11.627906976744185
Infinite Loop Rate: 2.3255813953488373

=================================================================================================
Failed Test Files: ['codeforces_242_A.py', 'atcoder_ABC169_C.py', 'atcoder_ABC168_C.py', 'codeforces_58_B.py', 'codeforces_622_A.py', 'atcoder_ABC051_A.py', 'atcoder_ABC155_E.py', 'codeforces_373_B.py', 'atcoder_AGC007_C.py', 'codeforces_79_A.py'] 
Failed Test Details: ['Filename: atcoder_ABC168_C.py Actual: 1.000076150972172\n Generated: 1.5567281636978751\n', 'Filename: codeforces_58_B.py Actual: 733035 \n244345 \n48869 \n1  Generated: 733035 244345 48869 1 ', 'Filename: codeforces_373_B.py Actual: 635520\n Generated: 635520.0\n', 'Filename: codeforces_79_A.py Actual: Ciel\n Generated: ', 'Filename: atcoder_ABC155_E.py Actual: 1\n Generated: 0\n', 'Filename: codeforces_242_A.py Actual: 6\n3 2\n4 2\n4 3\n5 2\n5 3\n5 4 Generated: ', 'Filename: atcoder_ABC169_C.py Actual: 1621439290561316\n Generated: 1621439290561315\n', 'Filename: codeforces_622_A.py Actual: 311 Generated: 311.0\n', 'Filename: atcoder_ABC051_A.py Actual: pnxnn asadasd asdasf\n\n Generated: ', 'Filename: atcoder_AGC007_C.py Actual: 649620280.95766068078000000000\n Generated: 649620280.9576602\n'] 
=================================================================================================
Runtime Error Files: ['codeforces_96_B.py', 'codeforces_171_A.py', 'codeforces_203_A.py', 'codeforces_99_A.py', 'atcoder_ABC143_A.py', 'atcoder_ABC174_C.py', 'atcoder_ABC132_F.py', 'codeforces_569_A.py', 'codeforces_189_A.py', 'codeforces_514_A.py'] 
Runtime Error Details: ['Filename: codeforces_99_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_99_A.py", line 4, in <module>\n    if sys.argv[1] == \'local\':\nIndexError: list index out of range\n', 'Filename: codeforces_514_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_514_A.py", line 20, in <module>\n    newNumber = newNumber + list[i] * (10 ** pow)\nOverflowError: int too large to convert to float\n', 'Filename: atcoder_ABC174_C.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/atcoder_ABC174_C.py", line 14, in <module>\n    if num in set:\nTypeError: argument of type \'type\' is not iterable\n', 'Filename: atcoder_ABC132_F.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/atcoder_ABC132_F.py", line 11, in <module>\n    q = len(len)\nTypeError: \'list\' object is not callable\n', 'Filename: codeforces_569_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_569_A.py", line 1, in <module>\n    t = int(input())\nValueError: invalid literal for int() with base 10: \'100000 3125 2\'\n', 'Filename: atcoder_ABC143_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/atcoder_ABC143_A.py", line 1, in <module>\n    A = int(input())\nValueError: invalid literal for int() with base 10: \'75 25\'\n', 'Filename: codeforces_189_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_189_A.py", line 3, in <module>\n    n = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'29 27 18 2\\n\'\n', 'Filename: codeforces_171_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_171_A.py", line 1, in <module>\n    a = int(input())\nValueError: invalid literal for int() with base 10: \'35005211 521595368\'\n', 'Filename: codeforces_96_B.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_96_B.py", line 17, in <module>\n    value = int(s, 2)\nValueError: invalid literal for int() with base 2: \'74\'\n', 'Filename: codeforces_203_A.py Error_type: Traceback (most recent call last):\n  File "/home/ali/Documents/CodeMind/translation_output/starcoder2/avatar/java/python-sanitized/codeforces_203_A.py", line 3, in <module>\n    points = int(sys.stdin.readline())\nValueError: invalid literal for int() with base 10: \'3 1 20 15 17 5\\n\'\n'] 
=================================================================================================
Compilation Error Files: ['atcoder_ABC120_C.py', 'codeforces_678_B.py', 'codeforces_86_A.py', 'codeforces_276_B.py', 'atcoder_ARC062_B.py', 'atcoder_ABC114_C.py', 'atcoder_ABC170_A.py'] 
=================================================================================================
Infinite Loop Files: ['atcoder_ARC102_C.py', 'codeforces_669_A.py'] 
=================================================================================================
